name: Ejecutar script cada hora

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora (UTC)
  workflow_dispatch:     # Permite ejecutarlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests pandas beautifulsoup4

      - name: Ejecutar script
        run: python main.py
        env:
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_RECIPIENT: $ {{ secrets.MAIL_RECIPIENT }}
          SIZE: ${{ secrets.SIZE }}
